// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RieltorComp.Data;

namespace RieltorComp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210321192934_FlagAdded")]
    partial class FlagAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("RieltorComp.Models.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isNew")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("RieltorComp.Models.Contracts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client_FIO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client_Passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner_FIO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner_Passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Property_Adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Service_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service_Done")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Service_Period")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service_Persent")
                        .HasColumnType("TEXT");

                    b.Property<double>("Service_Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("RieltorComp.Models.Properties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Living_Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number_Of_Rooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner_FIO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner_Passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isNew")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RieltorComp.Models.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("RieltorComp.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isNew")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
